'use strict';

process.env.BABEL_ENV = 'development';
process.env.NODE_ENV = 'development';

const isInteractive = process.stdout.isTTY;

const DEFAULT_PORT = parseInt( process.env.PORT, 10 ) || 3000;
const HOST = process.env.HOST || '0.0.0.0';

const createDevServerConfig = require( '../config/webpackDevServer.config' );
const configFactory = require( '../config/webpack.config' );

const webpack = require( 'webpack' );
const WebpackDevServer = require( 'webpack-dev-server' );

const config = configFactory( 'development' );
const protocol = process.env.HTTPS === 'true' ? 'https' : 'http';
const appName = require( '../package' ).name;

// Serve webpack assets generated by the compiler over a web server.
const serverConfig = createDevServerConfig();
const devServer = new WebpackDevServer( webpack( config ), serverConfig );
// Launch WebpackDevServer.
devServer.listen( HOST, err => {
  if ( err ) {
    return console.log( err );
  }
  if ( isInteractive ) {
    //
  }
  console.log( 'Starting the development server...\n' );
} );

[ 'SIGINT', 'SIGTERM' ].forEach( function( sig ) {
  process.on( sig, function() {
    devServer.close();
    process.exit();
  } );
} );
