module.exports = {
  cards: [
    { type: 'black', id: 'black_0', name: '0', value: '0' },
    { type: 'black', id: 'black_1', name: '1', value: '1' },
    { type: 'black', id: 'black_2', name: '2', value: '2' },
    { type: 'black', id: 'black_3', name: '3', value: '3' },
    { type: 'black', id: 'black_4', name: '4', value: '4' },
    { type: 'black', id: 'black_5', name: '5', value: '5' },
    { type: 'black', id: 'black_6', name: '6', value: '6' },
    { type: 'black', id: 'black_7', name: '7', value: '7' },
    { type: 'black', id: 'black_8', name: '8', value: '8' },
    { type: 'black', id: 'black_9', name: '9', value: '9' },
    { type: 'black', id: 'black_10', name: '10', value: '10' },
    { type: 'black', id: 'black_11', name: '11', value: '11' },
    { type: 'black', id: 'black_12', name: '-', value: '12', joker: true },
    { type: 'white', id: 'white_0', name: '0', value: '0' },
    { type: 'white', id: 'white_1', name: '1', value: '1' },
    { type: 'white', id: 'white_2', name: '2', value: '2' },
    { type: 'white', id: 'white_3', name: '3', value: '3' },
    { type: 'white', id: 'white_4', name: '4', value: '4' },
    { type: 'white', id: 'white_5', name: '5', value: '5' },
    { type: 'white', id: 'white_6', name: '6', value: '6' },
    { type: 'white', id: 'white_7', name: '7', value: '7' },
    { type: 'white', id: 'white_8', name: '8', value: '8' },
    { type: 'white', id: 'white_9', name: '9', value: '9' },
    { type: 'white', id: 'white_10', name: '10', value: '10' },
    { type: 'white', id: 'white_11', name: '11', value: '11' },
    { type: 'white', id: 'white_12', name: '-', value: '12', joker: true },
  ],
};
